/**
 * Generates pillar C's fixtures: a synthetic camera frame, the context packet the headset sends and
 * the response it gets back. `FixtureFrameSource` replays these in the Unity Editor, the server tests
 * run against them, and `pnpm sync:fixtures` copies them into the Unity project — so most of the
 * copilot can be built and tested with no headset in the room.
 *
 *   pnpm copilot:fixtures
 */
import "../env.js";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import jpeg from "jpeg-js";
import { Strict } from "@cutonce/schemas";
import { REPO_ROOT } from "../config.js";
import { ensureDir, writeJsonAtomic } from "../store/fs.js";

const OUT = join(REPO_ROOT, "data", "fixtures");
const W = 1280;
const H = 960;

type RGB = [number, number, number];
const canvas = Buffer.alloc(W * H * 4);

function fill(x: number, y: number, w: number, h: number, [r, g, b]: RGB) {
  for (let j = Math.max(0, y); j < Math.min(H, y + h); j++) {
    for (let i = Math.max(0, x); i < Math.min(W, x + w); i++) {
      const o = (j * W + i) * 4;
      canvas[o] = r; canvas[o + 1] = g; canvas[o + 2] = b; canvas[o + 3] = 255;
    }
  }
}

/** A plausible passthrough frame: a workshop wall and floor, a tabletop upside down, two legs on, two off. */
function scene() {
  for (let y = 0; y < H; y++) { // wall fading into floor, so the parts sit against something
    const t = y / H;
    fill(0, y, W, 1, [Math.round(96 + 40 * t), Math.round(98 + 38 * t), Math.round(104 + 34 * t)]);
  }
  fill(0, 620, W, H - 620, [120, 110, 98]);        // floor
  fill(180, 380, 900, 240, [196, 168, 122]);       // tabletop, upside down
  fill(180, 380, 900, 14, [214, 188, 146]);        // its lit edge
  fill(250, 200, 52, 190, [58, 58, 62]);           // left front leg, installed
  fill(958, 200, 52, 190, [58, 58, 62]);           // right front leg, installed
  fill(430, 470, 420, 46, [70, 72, 78]);           // cable tray, lying on the panel
  return jpeg.encode({ data: canvas, width: W, height: H }, 82).data;
}

/** Boxes match what `scene()` drew, so a projection bug shows up as boxes that do not line up. */
const visible = [
  { part_id: "part_tabletop", state: "built" as const, bbox_px: [180, 380, 900, 240] as [number, number, number, number], in_frame: 1, distance_m: 0.85 },
  { part_id: "part_left_front_leg", state: "built" as const, bbox_px: [250, 200, 52, 190] as [number, number, number, number], in_frame: 1, distance_m: 0.92 },
  { part_id: "part_right_front_leg", state: "built" as const, bbox_px: [958, 200, 52, 190] as [number, number, number, number], in_frame: 0.98, distance_m: 0.95 },
  { part_id: "part_left_rear_leg", state: "missing" as const, bbox_px: [250, 470, 52, 190] as [number, number, number, number], in_frame: 1, distance_m: 1.12 },
  { part_id: "part_right_rear_leg", state: "missing" as const, bbox_px: [958, 470, 52, 190] as [number, number, number, number], in_frame: 0.94, distance_m: 1.15 },
  { part_id: "part_cable_tray", state: "missing" as const, bbox_px: [430, 470, 420, 46] as [number, number, number, number], in_frame: 1, distance_m: 0.88 },
];

const camera = { width: W, height: H, fx: 870.1, fy: 870.4, cx: 640.2, cy: 481.7 };

const context = {
  context_id: "ctx_fixture_0001", assembly_id: "asm_fixture_desk", plan_revision: 1, state_version: 3,
  mode: "overlay" as const, selected_part_id: "part_cable_tray", selection_source: "controller_ray" as const,
  current_step_id: "step_07", visible_parts: visible, camera,
  scripted_query_id: null, client_sent_at: "2026-09-20T13:13:31.020Z",
};

const response = {
  turn_id: "turn_fixture_0001", transcript: "where does this cable go",
  answer_text: "Run it through the cable tray to the right rear leg, then clip it down the leg. That is on sheet E-1.",
  highlight_parts: ["part_power_cable", "part_cable_tray", "part_right_rear_leg"], highlight_style: "path" as const,
  drawing_refs: [{ document_id: "doc_desk_drawings", sheet_id: "sheet_e1", page: 2, chunk_id: "chunk_0042", title: "E-1 Wiring" }],
  action: null, confidence: 0.9, needs_clarification: false,
  audio_url: "/v1/audio/turn_fixture_0001", cached: false,
  timings_ms: { upload: 410, stt: 720, retrieve: 260, annotate: 90, llm: 2100, total_to_response: 3540 },
};

/** Where the frame was taken from: right-handed, +Y up, metres — the same frame as the plan. */
const pose = {
  frame: "frame_0001.jpg", camera,
  position: [0.5, 1.35, -1.1], rotation_quat: [0.0872, 0, 0, 0.9962],
  captured_at: "2026-09-20T13:13:30.880Z",
  note: "Synthetic. Generated by `pnpm copilot:fixtures` so the copilot can be built without a headset.",
};

ensureDir(OUT);
writeFileSync(join(OUT, "frame_0001.jpg"), Buffer.from(scene()));
writeJsonAtomic(join(OUT, "frame_0001.pose.json"), pose);
writeJsonAtomic(join(OUT, "context_packet.json"), Strict.CopilotContext.parse(context));
writeJsonAtomic(join(OUT, "copilot_response.json"), Strict.CopilotResponse.parse(response));
console.log(`wrote frame_0001.jpg (${W}×${H}), frame_0001.pose.json, context_packet.json and copilot_response.json to ${OUT}`);
